
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `MetaJam`=list(
        `type`="software", 
        `title`="MetaJam: Meta-Analysis for jamovi", 
        `author`="Darwish, N. E., Abdelmageed, A., Rezq, Z., & Osman, A. S. A.", 
        `year`=2026, 
        `publisher`="https://doi.org/10.5281/zenodo.21226177", 
        `url`="https://doi.org/10.5281/zenodo.21226177"), 
    `metaPackage`=list(
        `type`="article", 
        `author`="Balduzzi, S., R\u00FCcker, G., & Schwarzer, G.", 
        `year`=2019, 
        `title`="How to perform a meta-analysis with R: a practical tutorial", 
        `publisher`="Evidence-Based Mental Health", 
        `volume`=22, 
        `issue`=4, 
        `pages`="153-160", 
        `url`="https://doi.org/10.1136/ebmental-2019-300117"), 
    `metasensPackage`=list(
        `type`="software", 
        `author`="Schwarzer, G., Carpenter, J. R., & R\u00FCcker, G.", 
        `year`=2025, 
        `title`="metasens: Statistical Methods for Sensitivity Analysis in Meta-Analysis", 
        `publisher`="[R package]. Retrieved from https://cran.r-project.org/package=metasens", 
        `url`="https://cran.r-project.org/package=metasens"), 
    `metaforPackage`=list(
        `type`="article", 
        `author`="Viechtbauer, W.", 
        `year`=2010, 
        `title`="Conducting meta-analyses in R with the metafor package", 
        `publisher`="Journal of Statistical Software", 
        `volume`=36, 
        `issue`=3, 
        `pages`="1-48", 
        `url`="https://doi.org/10.18637/jss.v036.i03"))
