
# This file is automatically generated, you probably don't want to edit this

forestPlotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "forestPlotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            effectSize = NULL,
            ciLower = NULL,
            ciUpper = NULL,
            leftColumns = NULL,
            rightColumns = NULL, ...) {

            super$initialize(
                package="MetaJam",
                name="forestPlot",
                requiresData=TRUE,
                ...)

            private$..effectSize <- jmvcore::OptionVariable$new(
                "effectSize",
                effectSize,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ciLower <- jmvcore::OptionVariable$new(
                "ciLower",
                ciLower,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ciUpper <- jmvcore::OptionVariable$new(
                "ciUpper",
                ciUpper,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..leftColumns <- jmvcore::OptionVariables$new(
                "leftColumns",
                leftColumns,
                permitted=list(
                    "id",
                    "factor",
                    "numeric"))
            private$..rightColumns <- jmvcore::OptionVariables$new(
                "rightColumns",
                rightColumns,
                permitted=list(
                    "id",
                    "factor",
                    "numeric"))

            self$.addOption(private$..effectSize)
            self$.addOption(private$..ciLower)
            self$.addOption(private$..ciUpper)
            self$.addOption(private$..leftColumns)
            self$.addOption(private$..rightColumns)
        }),
    active = list(
        effectSize = function() private$..effectSize$value,
        ciLower = function() private$..ciLower$value,
        ciUpper = function() private$..ciUpper$value,
        leftColumns = function() private$..leftColumns$value,
        rightColumns = function() private$..rightColumns$value),
    private = list(
        ..effectSize = NA,
        ..ciLower = NA,
        ..ciUpper = NA,
        ..leftColumns = NA,
        ..rightColumns = NA)
)

forestPlotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "forestPlotResults",
    inherit = jmvcore::Group,
    active = list(
        plotSizeCache = function() private$.items[["plotSizeCache"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Forest Plot Builder")
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="plotSizeCache",
                            title="no title",
                            clearWith=list())}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                mode="vector",
                renderFun=".forestPlot",
                clearWith=list(
                    "effectSize",
                    "ciLower",
                    "ciUpper",
                    "leftColumns",
                    "rightColumns"),
                refs=list(
                    "MetaJam",
                    "forestploterPackage")))}))

forestPlotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "forestPlotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaJam",
                name = "forestPlot",
                version = c(1,0,0),
                options = options,
                results = forestPlotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Forest Plot Builder
#'
#' 
#' @param data .
#' @param effectSize .
#' @param ciLower .
#' @param ciUpper .
#' @param leftColumns .
#' @param rightColumns .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
forestPlot <- function(
    data,
    effectSize,
    ciLower,
    ciUpper,
    leftColumns,
    rightColumns) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("forestPlot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(effectSize)) effectSize <- jmvcore::resolveQuo(jmvcore::enquo(effectSize))
    if ( ! missing(ciLower)) ciLower <- jmvcore::resolveQuo(jmvcore::enquo(ciLower))
    if ( ! missing(ciUpper)) ciUpper <- jmvcore::resolveQuo(jmvcore::enquo(ciUpper))
    if ( ! missing(leftColumns)) leftColumns <- jmvcore::resolveQuo(jmvcore::enquo(leftColumns))
    if ( ! missing(rightColumns)) rightColumns <- jmvcore::resolveQuo(jmvcore::enquo(rightColumns))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(effectSize), effectSize, NULL),
            `if`( ! missing(ciLower), ciLower, NULL),
            `if`( ! missing(ciUpper), ciUpper, NULL),
            `if`( ! missing(leftColumns), leftColumns, NULL),
            `if`( ! missing(rightColumns), rightColumns, NULL))


    options <- forestPlotOptions$new(
        effectSize = effectSize,
        ciLower = ciLower,
        ciUpper = ciUpper,
        leftColumns = leftColumns,
        rightColumns = rightColumns)

    analysis <- forestPlotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

