#' Check Whether Required Variables Are Assigned
#'
#' Lightweight check that avoids triggering model computation.
#' Used as a guard in `.run()` instead of `is.null(self$model)` so
#' the model active binding is not forced unnecessarily.
#'
#' @param options A Jamovi options object.
#' @param vars Character vector of variable option names that must be assigned.
#' @return `TRUE` if all required variables are non-NULL, `FALSE` otherwise.
#' @noRd
hasRequiredVars <- function(options, vars) {
  for (opt in vars) {
    if (is.null(options[[opt]])) return(FALSE)
  }
  TRUE
}


#' Apply Cached Plot Dimensions
#'
#' Shared `.postInit()` helper. Restores plot dimensions from a hidden
#' `clearWith: []` cache element. Skips when the cache is empty (first
#' run), the plot is hidden, or `clearWith` cleared it (`isFilled()`
#' is FALSE). Essential for correct save/export sizing since
#' `fromProtoBuf()` does not restore `widthM`/`heightM`.
#'
#' @param image An Image result element (e.g., `self$results$plot`).
#' @param sizeCache A Group result element with `clearWith: []`
#'   (e.g., `self$results$plotSizeCache`).
#' @noRd
applyCachedSize <- function(image, sizeCache) {
  size <- sizeCache$state
  if (!is.null(size) && image$visible && image$isFilled()) {
    image$setSize(size$w, size$h)
  }
}


#' Initialize the Main Text Skeleton
#'
#' Called from `.init()` to show a titled HTML placeholder before the
#' model is available (e.g., when required variables are not yet assigned).
#' Uses `hasRequiredVars()` instead of checking the model directly to
#' avoid forcing the model active binding.
#'
#' @param textResult Html result element (e.g., `self$results$text`).
#' @param options The `self$options` object from a jamovi analysis.
#' @param requiredVars Character vector of option names that must be
#'   assigned for the model to compute.
#' @noRd
initMainText <- function(textResult, options, requiredVars) {
  if (textResult$visible && !hasRequiredVars(options, requiredVars)) {
    textResult$setContent(asHtml(title = "Meta-Analysis Summary"))
  }
}


#' Populate the Main Summary Text
#'
#' Called from `.run()` when the model is available. The `isFilled()`
#' guard skips recomputation when a non-model option changed and the
#' previous content is still valid (restored from protobuf via clearWith).
#'
#' @param textResult Html result element.
#' @param model A `meta` object (must not be `NULL`).
#' @noRd
populateMainText <- function(textResult, model) {
  if (!textResult$visible || textResult$isFilled()) {
    return()
  }
  textResult$setContent(asHtml(summary(model), title = "Meta-Analysis Summary"))
}


#' Strip Internal Environments to Prevent Memory Leaks
#'
#' R's `do.call()` injects entire function closures into the model's `$call`
#' when we invoke the functions dynamically. Additionally, the `meta` package
#' internally creates environments and closures for certain components (like
#' GLMM fits in metaprop/metabin). This utility strips these heavy closures and
#' formula environments out before caching the model to prevent massive
#' serialization size bloat. It applies to base `meta` objects (metacont,
#' metabin, metaprop, etc.).
#'
#' @param model A `meta` object.
#' @return The cleaned model.
#' @noRd
stripModel <- function(model) {
  # 1. Base models: strip the heavy do.call closures.
  model$call <- NULL

  # 2. GLMM models: strip internal closures and data environments generated by
  # meta. The data objects are actually environments that capture the R6
  # execution context.
  model$.glmm.common$call <- NULL
  model$.glmm.common$data <- NULL
  if (!is.null(model$.glmm.common$formula)) {
    environment(model$.glmm.common$formula) <- baseenv()
  }

  model$.glmm.random$call <- NULL
  model$.glmm.random$data <- NULL
  if (!is.null(model$.glmm.random$formula)) {
    environment(model$.glmm.random$formula) <- baseenv()
  }

  # NOTE: We currently do not support 3-level models (cluster) or unweighted
  # summary models (control = list(usw.common=TRUE, usw.random=TRUE)). If
  # MetaJam supports them in the future, be aware that metagen() returns
  # internal metafor::rma models in `model$rma.three.level`, `model$rma.usw.c`,
  # and `model$rma.usw.r`. These contain environments and formulas that leak the
  # R6 execution context and will need to be stripped here.

  model
}