
# This file is automatically generated, you probably don't want to edit this

metaGenOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaGenOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            sm = "GEN",
            inputMode = "se",
            studyLabel = NULL,
            effectSize = NULL,
            standardError = NULL,
            total = NULL,
            ciStudyLabel = NULL,
            ciEffectSize = NULL,
            ciLevel = 95,
            ciLower = NULL,
            ciUpper = NULL,
            ciTotal = NULL,
            model = "both",
            methodTau = "REML",
            methodRandomCi = "classic",
            prediction = FALSE,
            confidenceLevel = 95,
            summary = TRUE, ...) {

            super$initialize(
                package="MetaJam",
                name="metaGen",
                requiresData=TRUE,
                ...)

            private$..sm <- jmvcore::OptionList$new(
                "sm",
                sm,
                options=list(
                    "GEN",
                    "HR",
                    "MD",
                    "SMD",
                    "ROM",
                    "RR",
                    "OR",
                    "RD",
                    "VE",
                    "IRR",
                    "IRD",
                    "IRSD"),
                default="GEN")
            private$..inputMode <- jmvcore::OptionList$new(
                "inputMode",
                inputMode,
                options=list(
                    "se",
                    "ci"),
                default="se")
            private$..studyLabel <- jmvcore::OptionVariable$new(
                "studyLabel",
                studyLabel,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "id"))
            private$..effectSize <- jmvcore::OptionVariable$new(
                "effectSize",
                effectSize,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..standardError <- jmvcore::OptionVariable$new(
                "standardError",
                standardError,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..total <- jmvcore::OptionVariable$new(
                "total",
                total,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ciStudyLabel <- jmvcore::OptionVariable$new(
                "ciStudyLabel",
                ciStudyLabel,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "id"))
            private$..ciEffectSize <- jmvcore::OptionVariable$new(
                "ciEffectSize",
                ciEffectSize,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ciLevel <- jmvcore::OptionNumber$new(
                "ciLevel",
                ciLevel,
                min=50,
                max=99.9,
                default=95)
            private$..ciLower <- jmvcore::OptionVariable$new(
                "ciLower",
                ciLower,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ciUpper <- jmvcore::OptionVariable$new(
                "ciUpper",
                ciUpper,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ciTotal <- jmvcore::OptionVariable$new(
                "ciTotal",
                ciTotal,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "both",
                    "random",
                    "common"),
                default="both")
            private$..methodTau <- jmvcore::OptionList$new(
                "methodTau",
                methodTau,
                options=list(
                    "REML",
                    "PM",
                    "DL",
                    "ML",
                    "HS",
                    "SJ",
                    "HE",
                    "EB"),
                default="REML")
            private$..methodRandomCi <- jmvcore::OptionList$new(
                "methodRandomCi",
                methodRandomCi,
                options=list(
                    "classic",
                    "HK"),
                default="classic")
            private$..prediction <- jmvcore::OptionBool$new(
                "prediction",
                prediction,
                default=FALSE)
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                min=50,
                max=99.9,
                default=95)
            private$..summary <- jmvcore::OptionBool$new(
                "summary",
                summary,
                default=TRUE)

            self$.addOption(private$..sm)
            self$.addOption(private$..inputMode)
            self$.addOption(private$..studyLabel)
            self$.addOption(private$..effectSize)
            self$.addOption(private$..standardError)
            self$.addOption(private$..total)
            self$.addOption(private$..ciStudyLabel)
            self$.addOption(private$..ciEffectSize)
            self$.addOption(private$..ciLevel)
            self$.addOption(private$..ciLower)
            self$.addOption(private$..ciUpper)
            self$.addOption(private$..ciTotal)
            self$.addOption(private$..model)
            self$.addOption(private$..methodTau)
            self$.addOption(private$..methodRandomCi)
            self$.addOption(private$..prediction)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..summary)
        }),
    active = list(
        sm = function() private$..sm$value,
        inputMode = function() private$..inputMode$value,
        studyLabel = function() private$..studyLabel$value,
        effectSize = function() private$..effectSize$value,
        standardError = function() private$..standardError$value,
        total = function() private$..total$value,
        ciStudyLabel = function() private$..ciStudyLabel$value,
        ciEffectSize = function() private$..ciEffectSize$value,
        ciLevel = function() private$..ciLevel$value,
        ciLower = function() private$..ciLower$value,
        ciUpper = function() private$..ciUpper$value,
        ciTotal = function() private$..ciTotal$value,
        model = function() private$..model$value,
        methodTau = function() private$..methodTau$value,
        methodRandomCi = function() private$..methodRandomCi$value,
        prediction = function() private$..prediction$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        summary = function() private$..summary$value),
    private = list(
        ..sm = NA,
        ..inputMode = NA,
        ..studyLabel = NA,
        ..effectSize = NA,
        ..standardError = NA,
        ..total = NA,
        ..ciStudyLabel = NA,
        ..ciEffectSize = NA,
        ..ciLevel = NA,
        ..ciLower = NA,
        ..ciUpper = NA,
        ..ciTotal = NA,
        ..model = NA,
        ..methodTau = NA,
        ..methodRandomCi = NA,
        ..prediction = NA,
        ..confidenceLevel = NA,
        ..summary = NA)
)

metaGenResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaGenResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Precomputed Effect Sizes Meta-Analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                visible="(summary)",
                clearWith=list(
                    "sm",
                    "inputMode",
                    "studyLabel",
                    "effectSize",
                    "standardError",
                    "total",
                    "ciStudyLabel",
                    "ciEffectSize",
                    "ciLevel",
                    "ciLower",
                    "ciUpper",
                    "ciTotal",
                    "model",
                    "methodTau",
                    "methodRandomCi",
                    "prediction",
                    "confidenceLevel"),
                refs=list(
                    "MetaJam",
                    "metaPackage")))}))

metaGenBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaGenBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaJam",
                name = "metaGen",
                version = c(1,0,0),
                options = options,
                results = metaGenResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Precomputed Effect Sizes Meta-Analysis
#'
#' 
#' @param data .
#' @param sm .
#' @param inputMode .
#' @param studyLabel .
#' @param effectSize .
#' @param standardError .
#' @param total .
#' @param ciStudyLabel .
#' @param ciEffectSize .
#' @param ciLevel .
#' @param ciLower .
#' @param ciUpper .
#' @param ciTotal .
#' @param model .
#' @param methodTau .
#' @param methodRandomCi .
#' @param prediction .
#' @param confidenceLevel .
#' @param summary .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
metaGen <- function(
    data,
    sm = "GEN",
    inputMode = "se",
    studyLabel,
    effectSize,
    standardError,
    total,
    ciStudyLabel,
    ciEffectSize,
    ciLevel = 95,
    ciLower,
    ciUpper,
    ciTotal,
    model = "both",
    methodTau = "REML",
    methodRandomCi = "classic",
    prediction = FALSE,
    confidenceLevel = 95,
    summary = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("metaGen requires jmvcore to be installed (restart may be required)")

    if ( ! missing(studyLabel)) studyLabel <- jmvcore::resolveQuo(jmvcore::enquo(studyLabel))
    if ( ! missing(effectSize)) effectSize <- jmvcore::resolveQuo(jmvcore::enquo(effectSize))
    if ( ! missing(standardError)) standardError <- jmvcore::resolveQuo(jmvcore::enquo(standardError))
    if ( ! missing(total)) total <- jmvcore::resolveQuo(jmvcore::enquo(total))
    if ( ! missing(ciStudyLabel)) ciStudyLabel <- jmvcore::resolveQuo(jmvcore::enquo(ciStudyLabel))
    if ( ! missing(ciEffectSize)) ciEffectSize <- jmvcore::resolveQuo(jmvcore::enquo(ciEffectSize))
    if ( ! missing(ciLower)) ciLower <- jmvcore::resolveQuo(jmvcore::enquo(ciLower))
    if ( ! missing(ciUpper)) ciUpper <- jmvcore::resolveQuo(jmvcore::enquo(ciUpper))
    if ( ! missing(ciTotal)) ciTotal <- jmvcore::resolveQuo(jmvcore::enquo(ciTotal))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(studyLabel), studyLabel, NULL),
            `if`( ! missing(effectSize), effectSize, NULL),
            `if`( ! missing(standardError), standardError, NULL),
            `if`( ! missing(total), total, NULL),
            `if`( ! missing(ciStudyLabel), ciStudyLabel, NULL),
            `if`( ! missing(ciEffectSize), ciEffectSize, NULL),
            `if`( ! missing(ciLower), ciLower, NULL),
            `if`( ! missing(ciUpper), ciUpper, NULL),
            `if`( ! missing(ciTotal), ciTotal, NULL))


    options <- metaGenOptions$new(
        sm = sm,
        inputMode = inputMode,
        studyLabel = studyLabel,
        effectSize = effectSize,
        standardError = standardError,
        total = total,
        ciStudyLabel = ciStudyLabel,
        ciEffectSize = ciEffectSize,
        ciLevel = ciLevel,
        ciLower = ciLower,
        ciUpper = ciUpper,
        ciTotal = ciTotal,
        model = model,
        methodTau = methodTau,
        methodRandomCi = methodRandomCi,
        prediction = prediction,
        confidenceLevel = confidenceLevel,
        summary = summary)

    analysis <- metaGenClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

