#' Initialize a Text Skeleton
#'
#' Called from `.init()` to show a titled HTML placeholder before the
#' model is available (e.g., when required variables are not yet assigned).
#' Uses `hasRequiredVars()` instead of checking the model directly to
#' avoid forcing the model active binding.
#'
#' @param textResult Html result element (e.g., `self$results$text`).
#' @param options The `self$options` object from a jamovi analysis.
#' @param requiredVars Character vector of option names that must be
#'   assigned for the model to compute.
#' @param title A string to use as the HTML title.
#' @return `NULL` invisibly. Called for side effects.
#' @noRd
initText <- function(textResult, options, requiredVars, title) {
  if (textResult$visible && !hasRequiredVars(options, requiredVars)) {
    textResult$setContent(asHtml(title = title))
  }

  invisible(NULL)
}


#' Populate the Main Summary Text
#'
#' Called from `.run()` after `hasRequiredVars()` has passed.
#' Guards: skips when hidden, already filled (clearWith cache hit),
#' or model is NULL. We use the NULL check of the model here across our
#' module mainly as a proxy that required variables are available, which
#' we already verified in `.run()` before reaching this line. Although
#' redundant, we keep it for clarity.
#'
#' @param self The jamovi `self` object.
#' @return `NULL` invisibly. Called for side effects.
#' @noRd
populateMainText <- function(self) {
  textResult <- self$results$text
  if (!textResult$visible || textResult$isFilled() || is.null(self$model)) {
    return(invisible(NULL))
  }
  textResult$setContent(
    asHtml(summary(self$model), title = "Overall Summary")
  )

  invisible(NULL)
}


#' Check Whether Required Variables Are Assigned
#'
#' Lightweight check that avoids triggering model computation.
#' Used as a guard in `.run()` instead of `is.null(self$model)` so
#' the model active binding is not forced unnecessarily.
#'
#' @param options A Jamovi options object.
#' @param vars Character vector of variable option names that must be assigned.
#' @return `TRUE` if all required variables are non-NULL, `FALSE` otherwise.
#' @noRd
hasRequiredVars <- function(options, vars) {
  for (opt in vars) {
    if (is.null(options[[opt]])) return(FALSE)
  }
  TRUE
}


#' Prepare Model Objects for Fixed-Size Images
#'
#' Fixed-size images do not pass through `updateForestSize()`. Forest images
#' force their model during `.run()` when visible and stale because their
#' dynamic size must be measured before rendering. Fixed-size images have no
#' size-preparation step, so this helper prepares their model during `.run()`
#' before jamovi clears `self$data` and image rendering begins.
#'
#' @param model A model active binding, such as `self$model` or
#'   `self$metaRegModels`. It is only forced when an image needs rendering.
#' @param images An Image result element, or a list of Image result elements,
#'   that depend on the model.
#' @return `NULL` invisibly. Called for the side effect of forcing `model`.
#' @noRd
prepareModelForImages <- function(model, images) {
  if (!is.list(images)) {
    images <- list(images)
  }

  needsModel <- any(vapply(
    images,
    function(image) image$visible && !image$isFilled(),
    logical(1)
  ))

  if (needsModel) {
    force(model)
  }

  invisible(NULL)
}


#' Strip Internal Environments to Prevent Memory Leaks
#'
#' R's `do.call()` injects entire function closures into the model's `$call`
#' when we invoke the functions dynamically. Additionally, the `meta` package
#' internally creates environments and closures for certain components (like
#' GLMM fits in metaprop/metabin). This utility strips these heavy closures and
#' formula environments out before caching the model to prevent massive
#' serialization size bloat. It applies to base `meta` objects (metacont,
#' metabin, metaprop, etc.).
#'
#' @param model A `meta` object.
#' @return The cleaned model.
#' @noRd
stripModel <- function(model) {
  # 1. Base models: strip the heavy do.call closures.
  model$call <- NULL

  # 2. GLMM models: strip internal closures and data environments generated by
  # meta. The data objects are actually environments that capture the R6
  # execution context.
  model$.glmm.common$call <- NULL
  model$.glmm.common$data <- NULL
  if (!is.null(model$.glmm.common$formula)) {
    environment(model$.glmm.common$formula) <- baseenv()
  }

  model$.glmm.random$call <- NULL
  model$.glmm.random$data <- NULL
  if (!is.null(model$.glmm.random$formula)) {
    environment(model$.glmm.random$formula) <- baseenv()
  }

  # 3. Internal metafor::rma model objects (rma.mv for three-level, rma.uni for
  # user-specified weights). Only populated when keeprma = TRUE (default FALSE).
  # MetaJam never reads from them, and nothing in the meta package reads them
  # back either — they are write-only. Safe to NULL unconditionally.
  model$rma.three.level <- NULL
  model$rma.usw.c <- NULL
  model$rma.usw.r <- NULL

  model
}
