
# This file is automatically generated, you probably don't want to edit this

metaBinOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaBinOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            studyLabel = NULL,
            eventE = NULL,
            nE = NULL,
            eventC = NULL,
            nC = NULL,
            sm = "RR",
            method = "MH",
            correctionMethod = "only0",
            incr = 0.5,
            allstudies = FALSE,
            model = "both",
            methodTau = "REML",
            methodRandomCi = "classic",
            prediction = FALSE,
            confidenceLevel = 95,
            summary = TRUE, ...) {

            super$initialize(
                package="MetaJam",
                name="metaBin",
                requiresData=TRUE,
                ...)

            private$..studyLabel <- jmvcore::OptionVariable$new(
                "studyLabel",
                studyLabel,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "id"))
            private$..eventE <- jmvcore::OptionVariable$new(
                "eventE",
                eventE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nE <- jmvcore::OptionVariable$new(
                "nE",
                nE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..eventC <- jmvcore::OptionVariable$new(
                "eventC",
                eventC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nC <- jmvcore::OptionVariable$new(
                "nC",
                nC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sm <- jmvcore::OptionList$new(
                "sm",
                sm,
                options=list(
                    "RR",
                    "OR",
                    "RD",
                    "DOR",
                    "VE"),
                default="RR")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "MH",
                    "Inverse",
                    "Peto",
                    "SSW"),
                default="MH")
            private$..correctionMethod <- jmvcore::OptionList$new(
                "correctionMethod",
                correctionMethod,
                options=list(
                    "only0",
                    "if0all",
                    "all"),
                default="only0")
            private$..incr <- jmvcore::OptionNumber$new(
                "incr",
                incr,
                min=0,
                default=0.5)
            private$..allstudies <- jmvcore::OptionBool$new(
                "allstudies",
                allstudies,
                default=FALSE)
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "both",
                    "random",
                    "common"),
                default="both")
            private$..methodTau <- jmvcore::OptionList$new(
                "methodTau",
                methodTau,
                options=list(
                    "REML",
                    "PM",
                    "DL",
                    "ML",
                    "HS",
                    "SJ",
                    "HE",
                    "EB"),
                default="REML")
            private$..methodRandomCi <- jmvcore::OptionList$new(
                "methodRandomCi",
                methodRandomCi,
                options=list(
                    "classic",
                    "HK"),
                default="classic")
            private$..prediction <- jmvcore::OptionBool$new(
                "prediction",
                prediction,
                default=FALSE)
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                min=50,
                max=99.9,
                default=95)
            private$..summary <- jmvcore::OptionBool$new(
                "summary",
                summary,
                default=TRUE)

            self$.addOption(private$..studyLabel)
            self$.addOption(private$..eventE)
            self$.addOption(private$..nE)
            self$.addOption(private$..eventC)
            self$.addOption(private$..nC)
            self$.addOption(private$..sm)
            self$.addOption(private$..method)
            self$.addOption(private$..correctionMethod)
            self$.addOption(private$..incr)
            self$.addOption(private$..allstudies)
            self$.addOption(private$..model)
            self$.addOption(private$..methodTau)
            self$.addOption(private$..methodRandomCi)
            self$.addOption(private$..prediction)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..summary)
        }),
    active = list(
        studyLabel = function() private$..studyLabel$value,
        eventE = function() private$..eventE$value,
        nE = function() private$..nE$value,
        eventC = function() private$..eventC$value,
        nC = function() private$..nC$value,
        sm = function() private$..sm$value,
        method = function() private$..method$value,
        correctionMethod = function() private$..correctionMethod$value,
        incr = function() private$..incr$value,
        allstudies = function() private$..allstudies$value,
        model = function() private$..model$value,
        methodTau = function() private$..methodTau$value,
        methodRandomCi = function() private$..methodRandomCi$value,
        prediction = function() private$..prediction$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        summary = function() private$..summary$value),
    private = list(
        ..studyLabel = NA,
        ..eventE = NA,
        ..nE = NA,
        ..eventC = NA,
        ..nC = NA,
        ..sm = NA,
        ..method = NA,
        ..correctionMethod = NA,
        ..incr = NA,
        ..allstudies = NA,
        ..model = NA,
        ..methodTau = NA,
        ..methodRandomCi = NA,
        ..prediction = NA,
        ..confidenceLevel = NA,
        ..summary = NA)
)

metaBinResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaBinResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Binary Outcomes Meta-Analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                visible="(summary)",
                clearWith=list(
                    "studyLabel",
                    "eventE",
                    "nE",
                    "eventC",
                    "nC",
                    "sm",
                    "method",
                    "correctionMethod",
                    "incr",
                    "allstudies",
                    "model",
                    "methodTau",
                    "methodRandomCi",
                    "prediction",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))}))

metaBinBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaBinBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaJam",
                name = "metaBin",
                version = c(1,0,0),
                options = options,
                results = metaBinResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Binary Outcomes Meta-Analysis
#'
#' 
#' @param data .
#' @param studyLabel .
#' @param eventE .
#' @param nE .
#' @param eventC .
#' @param nC .
#' @param sm .
#' @param method .
#' @param correctionMethod .
#' @param incr .
#' @param allstudies .
#' @param model .
#' @param methodTau .
#' @param methodRandomCi .
#' @param prediction .
#' @param confidenceLevel .
#' @param summary .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
metaBin <- function(
    data,
    studyLabel,
    eventE,
    nE,
    eventC,
    nC,
    sm = "RR",
    method = "MH",
    correctionMethod = "only0",
    incr = 0.5,
    allstudies = FALSE,
    model = "both",
    methodTau = "REML",
    methodRandomCi = "classic",
    prediction = FALSE,
    confidenceLevel = 95,
    summary = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("metaBin requires jmvcore to be installed (restart may be required)")

    if ( ! missing(studyLabel)) studyLabel <- jmvcore::resolveQuo(jmvcore::enquo(studyLabel))
    if ( ! missing(eventE)) eventE <- jmvcore::resolveQuo(jmvcore::enquo(eventE))
    if ( ! missing(nE)) nE <- jmvcore::resolveQuo(jmvcore::enquo(nE))
    if ( ! missing(eventC)) eventC <- jmvcore::resolveQuo(jmvcore::enquo(eventC))
    if ( ! missing(nC)) nC <- jmvcore::resolveQuo(jmvcore::enquo(nC))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(studyLabel), studyLabel, NULL),
            `if`( ! missing(eventE), eventE, NULL),
            `if`( ! missing(nE), nE, NULL),
            `if`( ! missing(eventC), eventC, NULL),
            `if`( ! missing(nC), nC, NULL))


    options <- metaBinOptions$new(
        studyLabel = studyLabel,
        eventE = eventE,
        nE = nE,
        eventC = eventC,
        nC = nC,
        sm = sm,
        method = method,
        correctionMethod = correctionMethod,
        incr = incr,
        allstudies = allstudies,
        model = model,
        methodTau = methodTau,
        methodRandomCi = methodRandomCi,
        prediction = prediction,
        confidenceLevel = confidenceLevel,
        summary = summary)

    analysis <- metaBinClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

