
# This file is automatically generated, you probably don't want to edit this

metaGenOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaGenOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            sm = "GEN",
            studyLabel = NULL,
            effectSize = NULL,
            standardError = NULL,
            total = NULL,
            model = "both",
            methodTau = "REML",
            methodRandomCi = "classic",
            prediction = FALSE,
            confidenceLevel = 95,
            summary = TRUE, ...) {

            super$initialize(
                package="MetaJam",
                name="metaGen",
                requiresData=TRUE,
                ...)

            private$..sm <- jmvcore::OptionList$new(
                "sm",
                sm,
                options=list(
                    "GEN",
                    "HR",
                    "MD",
                    "SMD",
                    "ROM",
                    "RR",
                    "OR",
                    "RD",
                    "VE",
                    "IRR",
                    "IRD",
                    "IRSD"),
                default="GEN")
            private$..studyLabel <- jmvcore::OptionVariable$new(
                "studyLabel",
                studyLabel,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "id"))
            private$..effectSize <- jmvcore::OptionVariable$new(
                "effectSize",
                effectSize,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..standardError <- jmvcore::OptionVariable$new(
                "standardError",
                standardError,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..total <- jmvcore::OptionVariable$new(
                "total",
                total,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "both",
                    "random",
                    "common"),
                default="both")
            private$..methodTau <- jmvcore::OptionList$new(
                "methodTau",
                methodTau,
                options=list(
                    "REML",
                    "PM",
                    "DL",
                    "ML",
                    "HS",
                    "SJ",
                    "HE",
                    "EB"),
                default="REML")
            private$..methodRandomCi <- jmvcore::OptionList$new(
                "methodRandomCi",
                methodRandomCi,
                options=list(
                    "classic",
                    "HK"),
                default="classic")
            private$..prediction <- jmvcore::OptionBool$new(
                "prediction",
                prediction,
                default=FALSE)
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                min=50,
                max=99.9,
                default=95)
            private$..summary <- jmvcore::OptionBool$new(
                "summary",
                summary,
                default=TRUE)

            self$.addOption(private$..sm)
            self$.addOption(private$..studyLabel)
            self$.addOption(private$..effectSize)
            self$.addOption(private$..standardError)
            self$.addOption(private$..total)
            self$.addOption(private$..model)
            self$.addOption(private$..methodTau)
            self$.addOption(private$..methodRandomCi)
            self$.addOption(private$..prediction)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..summary)
        }),
    active = list(
        sm = function() private$..sm$value,
        studyLabel = function() private$..studyLabel$value,
        effectSize = function() private$..effectSize$value,
        standardError = function() private$..standardError$value,
        total = function() private$..total$value,
        model = function() private$..model$value,
        methodTau = function() private$..methodTau$value,
        methodRandomCi = function() private$..methodRandomCi$value,
        prediction = function() private$..prediction$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        summary = function() private$..summary$value),
    private = list(
        ..sm = NA,
        ..studyLabel = NA,
        ..effectSize = NA,
        ..standardError = NA,
        ..total = NA,
        ..model = NA,
        ..methodTau = NA,
        ..methodRandomCi = NA,
        ..prediction = NA,
        ..confidenceLevel = NA,
        ..summary = NA)
)

metaGenResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaGenResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Precomputed Effect Sizes Meta-Analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                visible="(summary)",
                clearWith=list(
                    "sm",
                    "studyLabel",
                    "effectSize",
                    "standardError",
                    "total",
                    "model",
                    "methodTau",
                    "methodRandomCi",
                    "prediction",
                    "confidenceLevel"),
                refs=list(
                    "MetaJam",
                    "metaPackage")))}))

metaGenBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaGenBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaJam",
                name = "metaGen",
                version = c(1,0,0),
                options = options,
                results = metaGenResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Precomputed Effect Sizes Meta-Analysis
#'
#' 
#' @param data .
#' @param sm .
#' @param studyLabel .
#' @param effectSize .
#' @param standardError .
#' @param total .
#' @param model .
#' @param methodTau .
#' @param methodRandomCi .
#' @param prediction .
#' @param confidenceLevel .
#' @param summary .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
metaGen <- function(
    data,
    sm = "GEN",
    studyLabel,
    effectSize,
    standardError,
    total,
    model = "both",
    methodTau = "REML",
    methodRandomCi = "classic",
    prediction = FALSE,
    confidenceLevel = 95,
    summary = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("metaGen requires jmvcore to be installed (restart may be required)")

    if ( ! missing(studyLabel)) studyLabel <- jmvcore::resolveQuo(jmvcore::enquo(studyLabel))
    if ( ! missing(effectSize)) effectSize <- jmvcore::resolveQuo(jmvcore::enquo(effectSize))
    if ( ! missing(standardError)) standardError <- jmvcore::resolveQuo(jmvcore::enquo(standardError))
    if ( ! missing(total)) total <- jmvcore::resolveQuo(jmvcore::enquo(total))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(studyLabel), studyLabel, NULL),
            `if`( ! missing(effectSize), effectSize, NULL),
            `if`( ! missing(standardError), standardError, NULL),
            `if`( ! missing(total), total, NULL))


    options <- metaGenOptions$new(
        sm = sm,
        studyLabel = studyLabel,
        effectSize = effectSize,
        standardError = standardError,
        total = total,
        model = model,
        methodTau = methodTau,
        methodRandomCi = methodRandomCi,
        prediction = prediction,
        confidenceLevel = confidenceLevel,
        summary = summary)

    analysis <- metaGenClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

