
# This file is automatically generated, you probably don't want to edit this

robOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "robOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            tool = "ROB2",
            rob2Study = NULL,
            rob2D1 = NULL,
            rob2D2 = NULL,
            rob2D3 = NULL,
            rob2D4 = NULL,
            rob2D5 = NULL,
            rob2Overall = NULL,
            rob2Weight = NULL,
            rob2ClusterStudy = NULL,
            rob2ClusterD1 = NULL,
            rob2ClusterD1b = NULL,
            rob2ClusterD2 = NULL,
            rob2ClusterD3 = NULL,
            rob2ClusterD4 = NULL,
            rob2ClusterD5 = NULL,
            rob2ClusterOverall = NULL,
            robinsIStudy = NULL,
            robinsID1 = NULL,
            robinsID2 = NULL,
            robinsID3 = NULL,
            robinsID4 = NULL,
            robinsID5 = NULL,
            robinsID6 = NULL,
            robinsID7 = NULL,
            robinsIOverall = NULL,
            robinsIWeight = NULL,
            robinsEStudy = NULL,
            robinsED1 = NULL,
            robinsED2 = NULL,
            robinsED3 = NULL,
            robinsED4 = NULL,
            robinsED5 = NULL,
            robinsED6 = NULL,
            robinsED7 = NULL,
            robinsEOverall = NULL,
            robinsEWeight = NULL,
            quadas2Study = NULL,
            quadas2D1 = NULL,
            quadas2D2 = NULL,
            quadas2D3 = NULL,
            quadas2D4 = NULL,
            quadas2Overall = NULL,
            quadas2Weight = NULL,
            quipsStudy = NULL,
            quipsD1 = NULL,
            quipsD2 = NULL,
            quipsD3 = NULL,
            quipsD4 = NULL,
            quipsD5 = NULL,
            quipsD6 = NULL,
            quipsOverall = NULL,
            quipsWeight = NULL,
            summaryPlot = TRUE,
            trafficPlot = TRUE,
            combinedPlot = FALSE,
            combinedOrder = "summaryFirst",
            combinedTags = "A",
            colour = "cochrane",
            pointSize = 10, ...) {

            super$initialize(
                package="MetaJam",
                name="rob",
                requiresData=TRUE,
                ...)

            private$..tool <- jmvcore::OptionList$new(
                "tool",
                tool,
                options=list(
                    "ROB2",
                    "ROB2-Cluster",
                    "ROBINS-I",
                    "ROBINS-E",
                    "QUADAS-2",
                    "QUIPS"),
                default="ROB2")
            private$..rob2Study <- jmvcore::OptionVariable$new(
                "rob2Study",
                rob2Study,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "id",
                    "factor"))
            private$..rob2D1 <- jmvcore::OptionVariable$new(
                "rob2D1",
                rob2D1,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2D2 <- jmvcore::OptionVariable$new(
                "rob2D2",
                rob2D2,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2D3 <- jmvcore::OptionVariable$new(
                "rob2D3",
                rob2D3,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2D4 <- jmvcore::OptionVariable$new(
                "rob2D4",
                rob2D4,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2D5 <- jmvcore::OptionVariable$new(
                "rob2D5",
                rob2D5,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2Overall <- jmvcore::OptionVariable$new(
                "rob2Overall",
                rob2Overall,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2Weight <- jmvcore::OptionVariable$new(
                "rob2Weight",
                rob2Weight,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..rob2ClusterStudy <- jmvcore::OptionVariable$new(
                "rob2ClusterStudy",
                rob2ClusterStudy,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "id",
                    "factor"))
            private$..rob2ClusterD1 <- jmvcore::OptionVariable$new(
                "rob2ClusterD1",
                rob2ClusterD1,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2ClusterD1b <- jmvcore::OptionVariable$new(
                "rob2ClusterD1b",
                rob2ClusterD1b,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2ClusterD2 <- jmvcore::OptionVariable$new(
                "rob2ClusterD2",
                rob2ClusterD2,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2ClusterD3 <- jmvcore::OptionVariable$new(
                "rob2ClusterD3",
                rob2ClusterD3,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2ClusterD4 <- jmvcore::OptionVariable$new(
                "rob2ClusterD4",
                rob2ClusterD4,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2ClusterD5 <- jmvcore::OptionVariable$new(
                "rob2ClusterD5",
                rob2ClusterD5,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..rob2ClusterOverall <- jmvcore::OptionVariable$new(
                "rob2ClusterOverall",
                rob2ClusterOverall,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsIStudy <- jmvcore::OptionVariable$new(
                "robinsIStudy",
                robinsIStudy,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "id",
                    "factor"))
            private$..robinsID1 <- jmvcore::OptionVariable$new(
                "robinsID1",
                robinsID1,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsID2 <- jmvcore::OptionVariable$new(
                "robinsID2",
                robinsID2,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsID3 <- jmvcore::OptionVariable$new(
                "robinsID3",
                robinsID3,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsID4 <- jmvcore::OptionVariable$new(
                "robinsID4",
                robinsID4,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsID5 <- jmvcore::OptionVariable$new(
                "robinsID5",
                robinsID5,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsID6 <- jmvcore::OptionVariable$new(
                "robinsID6",
                robinsID6,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsID7 <- jmvcore::OptionVariable$new(
                "robinsID7",
                robinsID7,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsIOverall <- jmvcore::OptionVariable$new(
                "robinsIOverall",
                robinsIOverall,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsIWeight <- jmvcore::OptionVariable$new(
                "robinsIWeight",
                robinsIWeight,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..robinsEStudy <- jmvcore::OptionVariable$new(
                "robinsEStudy",
                robinsEStudy,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "id",
                    "factor"))
            private$..robinsED1 <- jmvcore::OptionVariable$new(
                "robinsED1",
                robinsED1,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsED2 <- jmvcore::OptionVariable$new(
                "robinsED2",
                robinsED2,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsED3 <- jmvcore::OptionVariable$new(
                "robinsED3",
                robinsED3,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsED4 <- jmvcore::OptionVariable$new(
                "robinsED4",
                robinsED4,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsED5 <- jmvcore::OptionVariable$new(
                "robinsED5",
                robinsED5,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsED6 <- jmvcore::OptionVariable$new(
                "robinsED6",
                robinsED6,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsED7 <- jmvcore::OptionVariable$new(
                "robinsED7",
                robinsED7,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsEOverall <- jmvcore::OptionVariable$new(
                "robinsEOverall",
                robinsEOverall,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..robinsEWeight <- jmvcore::OptionVariable$new(
                "robinsEWeight",
                robinsEWeight,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..quadas2Study <- jmvcore::OptionVariable$new(
                "quadas2Study",
                quadas2Study,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "id",
                    "factor"))
            private$..quadas2D1 <- jmvcore::OptionVariable$new(
                "quadas2D1",
                quadas2D1,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quadas2D2 <- jmvcore::OptionVariable$new(
                "quadas2D2",
                quadas2D2,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quadas2D3 <- jmvcore::OptionVariable$new(
                "quadas2D3",
                quadas2D3,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quadas2D4 <- jmvcore::OptionVariable$new(
                "quadas2D4",
                quadas2D4,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quadas2Overall <- jmvcore::OptionVariable$new(
                "quadas2Overall",
                quadas2Overall,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quadas2Weight <- jmvcore::OptionVariable$new(
                "quadas2Weight",
                quadas2Weight,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..quipsStudy <- jmvcore::OptionVariable$new(
                "quipsStudy",
                quipsStudy,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "id",
                    "factor"))
            private$..quipsD1 <- jmvcore::OptionVariable$new(
                "quipsD1",
                quipsD1,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quipsD2 <- jmvcore::OptionVariable$new(
                "quipsD2",
                quipsD2,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quipsD3 <- jmvcore::OptionVariable$new(
                "quipsD3",
                quipsD3,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quipsD4 <- jmvcore::OptionVariable$new(
                "quipsD4",
                quipsD4,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quipsD5 <- jmvcore::OptionVariable$new(
                "quipsD5",
                quipsD5,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quipsD6 <- jmvcore::OptionVariable$new(
                "quipsD6",
                quipsD6,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quipsOverall <- jmvcore::OptionVariable$new(
                "quipsOverall",
                quipsOverall,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..quipsWeight <- jmvcore::OptionVariable$new(
                "quipsWeight",
                quipsWeight,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..summaryPlot <- jmvcore::OptionBool$new(
                "summaryPlot",
                summaryPlot,
                default=TRUE)
            private$..trafficPlot <- jmvcore::OptionBool$new(
                "trafficPlot",
                trafficPlot,
                default=TRUE)
            private$..combinedPlot <- jmvcore::OptionBool$new(
                "combinedPlot",
                combinedPlot,
                default=FALSE)
            private$..combinedOrder <- jmvcore::OptionList$new(
                "combinedOrder",
                combinedOrder,
                options=list(
                    "summaryFirst",
                    "trafficFirst"),
                default="summaryFirst")
            private$..combinedTags <- jmvcore::OptionList$new(
                "combinedTags",
                combinedTags,
                options=list(
                    "A",
                    "1",
                    "I",
                    "none"),
                default="A")
            private$..colour <- jmvcore::OptionList$new(
                "colour",
                colour,
                options=list(
                    "cochrane",
                    "colourblind"),
                default="cochrane")
            private$..pointSize <- jmvcore::OptionNumber$new(
                "pointSize",
                pointSize,
                default=10,
                min=0)

            self$.addOption(private$..tool)
            self$.addOption(private$..rob2Study)
            self$.addOption(private$..rob2D1)
            self$.addOption(private$..rob2D2)
            self$.addOption(private$..rob2D3)
            self$.addOption(private$..rob2D4)
            self$.addOption(private$..rob2D5)
            self$.addOption(private$..rob2Overall)
            self$.addOption(private$..rob2Weight)
            self$.addOption(private$..rob2ClusterStudy)
            self$.addOption(private$..rob2ClusterD1)
            self$.addOption(private$..rob2ClusterD1b)
            self$.addOption(private$..rob2ClusterD2)
            self$.addOption(private$..rob2ClusterD3)
            self$.addOption(private$..rob2ClusterD4)
            self$.addOption(private$..rob2ClusterD5)
            self$.addOption(private$..rob2ClusterOverall)
            self$.addOption(private$..robinsIStudy)
            self$.addOption(private$..robinsID1)
            self$.addOption(private$..robinsID2)
            self$.addOption(private$..robinsID3)
            self$.addOption(private$..robinsID4)
            self$.addOption(private$..robinsID5)
            self$.addOption(private$..robinsID6)
            self$.addOption(private$..robinsID7)
            self$.addOption(private$..robinsIOverall)
            self$.addOption(private$..robinsIWeight)
            self$.addOption(private$..robinsEStudy)
            self$.addOption(private$..robinsED1)
            self$.addOption(private$..robinsED2)
            self$.addOption(private$..robinsED3)
            self$.addOption(private$..robinsED4)
            self$.addOption(private$..robinsED5)
            self$.addOption(private$..robinsED6)
            self$.addOption(private$..robinsED7)
            self$.addOption(private$..robinsEOverall)
            self$.addOption(private$..robinsEWeight)
            self$.addOption(private$..quadas2Study)
            self$.addOption(private$..quadas2D1)
            self$.addOption(private$..quadas2D2)
            self$.addOption(private$..quadas2D3)
            self$.addOption(private$..quadas2D4)
            self$.addOption(private$..quadas2Overall)
            self$.addOption(private$..quadas2Weight)
            self$.addOption(private$..quipsStudy)
            self$.addOption(private$..quipsD1)
            self$.addOption(private$..quipsD2)
            self$.addOption(private$..quipsD3)
            self$.addOption(private$..quipsD4)
            self$.addOption(private$..quipsD5)
            self$.addOption(private$..quipsD6)
            self$.addOption(private$..quipsOverall)
            self$.addOption(private$..quipsWeight)
            self$.addOption(private$..summaryPlot)
            self$.addOption(private$..trafficPlot)
            self$.addOption(private$..combinedPlot)
            self$.addOption(private$..combinedOrder)
            self$.addOption(private$..combinedTags)
            self$.addOption(private$..colour)
            self$.addOption(private$..pointSize)
        }),
    active = list(
        tool = function() private$..tool$value,
        rob2Study = function() private$..rob2Study$value,
        rob2D1 = function() private$..rob2D1$value,
        rob2D2 = function() private$..rob2D2$value,
        rob2D3 = function() private$..rob2D3$value,
        rob2D4 = function() private$..rob2D4$value,
        rob2D5 = function() private$..rob2D5$value,
        rob2Overall = function() private$..rob2Overall$value,
        rob2Weight = function() private$..rob2Weight$value,
        rob2ClusterStudy = function() private$..rob2ClusterStudy$value,
        rob2ClusterD1 = function() private$..rob2ClusterD1$value,
        rob2ClusterD1b = function() private$..rob2ClusterD1b$value,
        rob2ClusterD2 = function() private$..rob2ClusterD2$value,
        rob2ClusterD3 = function() private$..rob2ClusterD3$value,
        rob2ClusterD4 = function() private$..rob2ClusterD4$value,
        rob2ClusterD5 = function() private$..rob2ClusterD5$value,
        rob2ClusterOverall = function() private$..rob2ClusterOverall$value,
        robinsIStudy = function() private$..robinsIStudy$value,
        robinsID1 = function() private$..robinsID1$value,
        robinsID2 = function() private$..robinsID2$value,
        robinsID3 = function() private$..robinsID3$value,
        robinsID4 = function() private$..robinsID4$value,
        robinsID5 = function() private$..robinsID5$value,
        robinsID6 = function() private$..robinsID6$value,
        robinsID7 = function() private$..robinsID7$value,
        robinsIOverall = function() private$..robinsIOverall$value,
        robinsIWeight = function() private$..robinsIWeight$value,
        robinsEStudy = function() private$..robinsEStudy$value,
        robinsED1 = function() private$..robinsED1$value,
        robinsED2 = function() private$..robinsED2$value,
        robinsED3 = function() private$..robinsED3$value,
        robinsED4 = function() private$..robinsED4$value,
        robinsED5 = function() private$..robinsED5$value,
        robinsED6 = function() private$..robinsED6$value,
        robinsED7 = function() private$..robinsED7$value,
        robinsEOverall = function() private$..robinsEOverall$value,
        robinsEWeight = function() private$..robinsEWeight$value,
        quadas2Study = function() private$..quadas2Study$value,
        quadas2D1 = function() private$..quadas2D1$value,
        quadas2D2 = function() private$..quadas2D2$value,
        quadas2D3 = function() private$..quadas2D3$value,
        quadas2D4 = function() private$..quadas2D4$value,
        quadas2Overall = function() private$..quadas2Overall$value,
        quadas2Weight = function() private$..quadas2Weight$value,
        quipsStudy = function() private$..quipsStudy$value,
        quipsD1 = function() private$..quipsD1$value,
        quipsD2 = function() private$..quipsD2$value,
        quipsD3 = function() private$..quipsD3$value,
        quipsD4 = function() private$..quipsD4$value,
        quipsD5 = function() private$..quipsD5$value,
        quipsD6 = function() private$..quipsD6$value,
        quipsOverall = function() private$..quipsOverall$value,
        quipsWeight = function() private$..quipsWeight$value,
        summaryPlot = function() private$..summaryPlot$value,
        trafficPlot = function() private$..trafficPlot$value,
        combinedPlot = function() private$..combinedPlot$value,
        combinedOrder = function() private$..combinedOrder$value,
        combinedTags = function() private$..combinedTags$value,
        colour = function() private$..colour$value,
        pointSize = function() private$..pointSize$value),
    private = list(
        ..tool = NA,
        ..rob2Study = NA,
        ..rob2D1 = NA,
        ..rob2D2 = NA,
        ..rob2D3 = NA,
        ..rob2D4 = NA,
        ..rob2D5 = NA,
        ..rob2Overall = NA,
        ..rob2Weight = NA,
        ..rob2ClusterStudy = NA,
        ..rob2ClusterD1 = NA,
        ..rob2ClusterD1b = NA,
        ..rob2ClusterD2 = NA,
        ..rob2ClusterD3 = NA,
        ..rob2ClusterD4 = NA,
        ..rob2ClusterD5 = NA,
        ..rob2ClusterOverall = NA,
        ..robinsIStudy = NA,
        ..robinsID1 = NA,
        ..robinsID2 = NA,
        ..robinsID3 = NA,
        ..robinsID4 = NA,
        ..robinsID5 = NA,
        ..robinsID6 = NA,
        ..robinsID7 = NA,
        ..robinsIOverall = NA,
        ..robinsIWeight = NA,
        ..robinsEStudy = NA,
        ..robinsED1 = NA,
        ..robinsED2 = NA,
        ..robinsED3 = NA,
        ..robinsED4 = NA,
        ..robinsED5 = NA,
        ..robinsED6 = NA,
        ..robinsED7 = NA,
        ..robinsEOverall = NA,
        ..robinsEWeight = NA,
        ..quadas2Study = NA,
        ..quadas2D1 = NA,
        ..quadas2D2 = NA,
        ..quadas2D3 = NA,
        ..quadas2D4 = NA,
        ..quadas2Overall = NA,
        ..quadas2Weight = NA,
        ..quipsStudy = NA,
        ..quipsD1 = NA,
        ..quipsD2 = NA,
        ..quipsD3 = NA,
        ..quipsD4 = NA,
        ..quipsD5 = NA,
        ..quipsD6 = NA,
        ..quipsOverall = NA,
        ..quipsWeight = NA,
        ..summaryPlot = NA,
        ..trafficPlot = NA,
        ..combinedPlot = NA,
        ..combinedOrder = NA,
        ..combinedTags = NA,
        ..colour = NA,
        ..pointSize = NA)
)

robResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "robResults",
    inherit = jmvcore::Group,
    active = list(
        summaryPlot = function() private$.items[["summaryPlot"]],
        trafficPlotSizeCache = function() private$.items[["trafficPlotSizeCache"]],
        trafficPlot = function() private$.items[["trafficPlot"]],
        combinedPlot = function() private$.items[["combinedPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Risk of Bias Plots")
            self$add(jmvcore::Image$new(
                options=options,
                name="summaryPlot",
                title="Summary Plot",
                width=576,
                height=174,
                renderFun=".summaryPlot",
                visible="(summaryPlot && tool != \"ROB2-Cluster\")",
                clearWith=list(
                    "tool",
                    "rob2Study",
                    "rob2D1",
                    "rob2D2",
                    "rob2D3",
                    "rob2D4",
                    "rob2D5",
                    "rob2Overall",
                    "rob2Weight",
                    "robinsIStudy",
                    "robinsID1",
                    "robinsID2",
                    "robinsID3",
                    "robinsID4",
                    "robinsID5",
                    "robinsID6",
                    "robinsID7",
                    "robinsIOverall",
                    "robinsIWeight",
                    "robinsEStudy",
                    "robinsED1",
                    "robinsED2",
                    "robinsED3",
                    "robinsED4",
                    "robinsED5",
                    "robinsED6",
                    "robinsED7",
                    "robinsEOverall",
                    "robinsEWeight",
                    "quadas2Study",
                    "quadas2D1",
                    "quadas2D2",
                    "quadas2D3",
                    "quadas2D4",
                    "quadas2Overall",
                    "quadas2Weight",
                    "quipsStudy",
                    "quipsD1",
                    "quipsD2",
                    "quipsD3",
                    "quipsD4",
                    "quipsD5",
                    "quipsD6",
                    "quipsOverall",
                    "quipsWeight",
                    "colour"),
                refs=list(
                    "MetaJam",
                    "robvisPackage")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="trafficPlotSizeCache",
                            title="no title",
                            clearWith=list())}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="trafficPlot",
                title="Traffic Light Plot",
                renderFun=".trafficPlot",
                visible="(trafficPlot)",
                clearWith=list(
                    "tool",
                    "rob2Study",
                    "rob2D1",
                    "rob2D2",
                    "rob2D3",
                    "rob2D4",
                    "rob2D5",
                    "rob2Overall",
                    "rob2ClusterStudy",
                    "rob2ClusterD1",
                    "rob2ClusterD1b",
                    "rob2ClusterD2",
                    "rob2ClusterD3",
                    "rob2ClusterD4",
                    "rob2ClusterD5",
                    "rob2ClusterOverall",
                    "robinsIStudy",
                    "robinsID1",
                    "robinsID2",
                    "robinsID3",
                    "robinsID4",
                    "robinsID5",
                    "robinsID6",
                    "robinsID7",
                    "robinsIOverall",
                    "robinsEStudy",
                    "robinsED1",
                    "robinsED2",
                    "robinsED3",
                    "robinsED4",
                    "robinsED5",
                    "robinsED6",
                    "robinsED7",
                    "robinsEOverall",
                    "quadas2Study",
                    "quadas2D1",
                    "quadas2D2",
                    "quadas2D3",
                    "quadas2D4",
                    "quadas2Overall",
                    "quipsStudy",
                    "quipsD1",
                    "quipsD2",
                    "quipsD3",
                    "quipsD4",
                    "quipsD5",
                    "quipsD6",
                    "quipsOverall",
                    "colour",
                    "pointSize"),
                refs=list(
                    "MetaJam",
                    "robvisPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="combinedPlot",
                title="Combined Plot",
                renderFun=".combinedPlot",
                visible="(combinedPlot && tool != \"ROB2-Cluster\")",
                clearWith=list(
                    "tool",
                    "rob2Study",
                    "rob2D1",
                    "rob2D2",
                    "rob2D3",
                    "rob2D4",
                    "rob2D5",
                    "rob2Overall",
                    "rob2Weight",
                    "robinsIStudy",
                    "robinsID1",
                    "robinsID2",
                    "robinsID3",
                    "robinsID4",
                    "robinsID5",
                    "robinsID6",
                    "robinsID7",
                    "robinsIOverall",
                    "robinsIWeight",
                    "robinsEStudy",
                    "robinsED1",
                    "robinsED2",
                    "robinsED3",
                    "robinsED4",
                    "robinsED5",
                    "robinsED6",
                    "robinsED7",
                    "robinsEOverall",
                    "robinsEWeight",
                    "quadas2Study",
                    "quadas2D1",
                    "quadas2D2",
                    "quadas2D3",
                    "quadas2D4",
                    "quadas2Overall",
                    "quadas2Weight",
                    "quipsStudy",
                    "quipsD1",
                    "quipsD2",
                    "quipsD3",
                    "quipsD4",
                    "quipsD5",
                    "quipsD6",
                    "quipsOverall",
                    "quipsWeight",
                    "colour",
                    "pointSize",
                    "combinedOrder",
                    "combinedTags"),
                refs=list(
                    "MetaJam",
                    "robvisPackage")))}))

robBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "robBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaJam",
                name = "rob",
                version = c(1,0,0),
                options = options,
                results = robResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Risk of Bias Plots
#'
#' 
#' @param data .
#' @param tool .
#' @param rob2Study .
#' @param rob2D1 .
#' @param rob2D2 .
#' @param rob2D3 .
#' @param rob2D4 .
#' @param rob2D5 .
#' @param rob2Overall .
#' @param rob2Weight .
#' @param rob2ClusterStudy .
#' @param rob2ClusterD1 .
#' @param rob2ClusterD1b .
#' @param rob2ClusterD2 .
#' @param rob2ClusterD3 .
#' @param rob2ClusterD4 .
#' @param rob2ClusterD5 .
#' @param rob2ClusterOverall .
#' @param robinsIStudy .
#' @param robinsID1 .
#' @param robinsID2 .
#' @param robinsID3 .
#' @param robinsID4 .
#' @param robinsID5 .
#' @param robinsID6 .
#' @param robinsID7 .
#' @param robinsIOverall .
#' @param robinsIWeight .
#' @param robinsEStudy .
#' @param robinsED1 .
#' @param robinsED2 .
#' @param robinsED3 .
#' @param robinsED4 .
#' @param robinsED5 .
#' @param robinsED6 .
#' @param robinsED7 .
#' @param robinsEOverall .
#' @param robinsEWeight .
#' @param quadas2Study .
#' @param quadas2D1 .
#' @param quadas2D2 .
#' @param quadas2D3 .
#' @param quadas2D4 .
#' @param quadas2Overall .
#' @param quadas2Weight .
#' @param quipsStudy .
#' @param quipsD1 .
#' @param quipsD2 .
#' @param quipsD3 .
#' @param quipsD4 .
#' @param quipsD5 .
#' @param quipsD6 .
#' @param quipsOverall .
#' @param quipsWeight .
#' @param summaryPlot .
#' @param trafficPlot .
#' @param combinedPlot .
#' @param combinedOrder .
#' @param combinedTags .
#' @param colour .
#' @param pointSize .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summaryPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$trafficPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$combinedPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
rob <- function(
    data,
    tool = "ROB2",
    rob2Study,
    rob2D1,
    rob2D2,
    rob2D3,
    rob2D4,
    rob2D5,
    rob2Overall,
    rob2Weight,
    rob2ClusterStudy,
    rob2ClusterD1,
    rob2ClusterD1b,
    rob2ClusterD2,
    rob2ClusterD3,
    rob2ClusterD4,
    rob2ClusterD5,
    rob2ClusterOverall,
    robinsIStudy,
    robinsID1,
    robinsID2,
    robinsID3,
    robinsID4,
    robinsID5,
    robinsID6,
    robinsID7,
    robinsIOverall,
    robinsIWeight,
    robinsEStudy,
    robinsED1,
    robinsED2,
    robinsED3,
    robinsED4,
    robinsED5,
    robinsED6,
    robinsED7,
    robinsEOverall,
    robinsEWeight,
    quadas2Study,
    quadas2D1,
    quadas2D2,
    quadas2D3,
    quadas2D4,
    quadas2Overall,
    quadas2Weight,
    quipsStudy,
    quipsD1,
    quipsD2,
    quipsD3,
    quipsD4,
    quipsD5,
    quipsD6,
    quipsOverall,
    quipsWeight,
    summaryPlot = TRUE,
    trafficPlot = TRUE,
    combinedPlot = FALSE,
    combinedOrder = "summaryFirst",
    combinedTags = "A",
    colour = "cochrane",
    pointSize = 10) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("rob requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rob2Study)) rob2Study <- jmvcore::resolveQuo(jmvcore::enquo(rob2Study))
    if ( ! missing(rob2D1)) rob2D1 <- jmvcore::resolveQuo(jmvcore::enquo(rob2D1))
    if ( ! missing(rob2D2)) rob2D2 <- jmvcore::resolveQuo(jmvcore::enquo(rob2D2))
    if ( ! missing(rob2D3)) rob2D3 <- jmvcore::resolveQuo(jmvcore::enquo(rob2D3))
    if ( ! missing(rob2D4)) rob2D4 <- jmvcore::resolveQuo(jmvcore::enquo(rob2D4))
    if ( ! missing(rob2D5)) rob2D5 <- jmvcore::resolveQuo(jmvcore::enquo(rob2D5))
    if ( ! missing(rob2Overall)) rob2Overall <- jmvcore::resolveQuo(jmvcore::enquo(rob2Overall))
    if ( ! missing(rob2Weight)) rob2Weight <- jmvcore::resolveQuo(jmvcore::enquo(rob2Weight))
    if ( ! missing(rob2ClusterStudy)) rob2ClusterStudy <- jmvcore::resolveQuo(jmvcore::enquo(rob2ClusterStudy))
    if ( ! missing(rob2ClusterD1)) rob2ClusterD1 <- jmvcore::resolveQuo(jmvcore::enquo(rob2ClusterD1))
    if ( ! missing(rob2ClusterD1b)) rob2ClusterD1b <- jmvcore::resolveQuo(jmvcore::enquo(rob2ClusterD1b))
    if ( ! missing(rob2ClusterD2)) rob2ClusterD2 <- jmvcore::resolveQuo(jmvcore::enquo(rob2ClusterD2))
    if ( ! missing(rob2ClusterD3)) rob2ClusterD3 <- jmvcore::resolveQuo(jmvcore::enquo(rob2ClusterD3))
    if ( ! missing(rob2ClusterD4)) rob2ClusterD4 <- jmvcore::resolveQuo(jmvcore::enquo(rob2ClusterD4))
    if ( ! missing(rob2ClusterD5)) rob2ClusterD5 <- jmvcore::resolveQuo(jmvcore::enquo(rob2ClusterD5))
    if ( ! missing(rob2ClusterOverall)) rob2ClusterOverall <- jmvcore::resolveQuo(jmvcore::enquo(rob2ClusterOverall))
    if ( ! missing(robinsIStudy)) robinsIStudy <- jmvcore::resolveQuo(jmvcore::enquo(robinsIStudy))
    if ( ! missing(robinsID1)) robinsID1 <- jmvcore::resolveQuo(jmvcore::enquo(robinsID1))
    if ( ! missing(robinsID2)) robinsID2 <- jmvcore::resolveQuo(jmvcore::enquo(robinsID2))
    if ( ! missing(robinsID3)) robinsID3 <- jmvcore::resolveQuo(jmvcore::enquo(robinsID3))
    if ( ! missing(robinsID4)) robinsID4 <- jmvcore::resolveQuo(jmvcore::enquo(robinsID4))
    if ( ! missing(robinsID5)) robinsID5 <- jmvcore::resolveQuo(jmvcore::enquo(robinsID5))
    if ( ! missing(robinsID6)) robinsID6 <- jmvcore::resolveQuo(jmvcore::enquo(robinsID6))
    if ( ! missing(robinsID7)) robinsID7 <- jmvcore::resolveQuo(jmvcore::enquo(robinsID7))
    if ( ! missing(robinsIOverall)) robinsIOverall <- jmvcore::resolveQuo(jmvcore::enquo(robinsIOverall))
    if ( ! missing(robinsIWeight)) robinsIWeight <- jmvcore::resolveQuo(jmvcore::enquo(robinsIWeight))
    if ( ! missing(robinsEStudy)) robinsEStudy <- jmvcore::resolveQuo(jmvcore::enquo(robinsEStudy))
    if ( ! missing(robinsED1)) robinsED1 <- jmvcore::resolveQuo(jmvcore::enquo(robinsED1))
    if ( ! missing(robinsED2)) robinsED2 <- jmvcore::resolveQuo(jmvcore::enquo(robinsED2))
    if ( ! missing(robinsED3)) robinsED3 <- jmvcore::resolveQuo(jmvcore::enquo(robinsED3))
    if ( ! missing(robinsED4)) robinsED4 <- jmvcore::resolveQuo(jmvcore::enquo(robinsED4))
    if ( ! missing(robinsED5)) robinsED5 <- jmvcore::resolveQuo(jmvcore::enquo(robinsED5))
    if ( ! missing(robinsED6)) robinsED6 <- jmvcore::resolveQuo(jmvcore::enquo(robinsED6))
    if ( ! missing(robinsED7)) robinsED7 <- jmvcore::resolveQuo(jmvcore::enquo(robinsED7))
    if ( ! missing(robinsEOverall)) robinsEOverall <- jmvcore::resolveQuo(jmvcore::enquo(robinsEOverall))
    if ( ! missing(robinsEWeight)) robinsEWeight <- jmvcore::resolveQuo(jmvcore::enquo(robinsEWeight))
    if ( ! missing(quadas2Study)) quadas2Study <- jmvcore::resolveQuo(jmvcore::enquo(quadas2Study))
    if ( ! missing(quadas2D1)) quadas2D1 <- jmvcore::resolveQuo(jmvcore::enquo(quadas2D1))
    if ( ! missing(quadas2D2)) quadas2D2 <- jmvcore::resolveQuo(jmvcore::enquo(quadas2D2))
    if ( ! missing(quadas2D3)) quadas2D3 <- jmvcore::resolveQuo(jmvcore::enquo(quadas2D3))
    if ( ! missing(quadas2D4)) quadas2D4 <- jmvcore::resolveQuo(jmvcore::enquo(quadas2D4))
    if ( ! missing(quadas2Overall)) quadas2Overall <- jmvcore::resolveQuo(jmvcore::enquo(quadas2Overall))
    if ( ! missing(quadas2Weight)) quadas2Weight <- jmvcore::resolveQuo(jmvcore::enquo(quadas2Weight))
    if ( ! missing(quipsStudy)) quipsStudy <- jmvcore::resolveQuo(jmvcore::enquo(quipsStudy))
    if ( ! missing(quipsD1)) quipsD1 <- jmvcore::resolveQuo(jmvcore::enquo(quipsD1))
    if ( ! missing(quipsD2)) quipsD2 <- jmvcore::resolveQuo(jmvcore::enquo(quipsD2))
    if ( ! missing(quipsD3)) quipsD3 <- jmvcore::resolveQuo(jmvcore::enquo(quipsD3))
    if ( ! missing(quipsD4)) quipsD4 <- jmvcore::resolveQuo(jmvcore::enquo(quipsD4))
    if ( ! missing(quipsD5)) quipsD5 <- jmvcore::resolveQuo(jmvcore::enquo(quipsD5))
    if ( ! missing(quipsD6)) quipsD6 <- jmvcore::resolveQuo(jmvcore::enquo(quipsD6))
    if ( ! missing(quipsOverall)) quipsOverall <- jmvcore::resolveQuo(jmvcore::enquo(quipsOverall))
    if ( ! missing(quipsWeight)) quipsWeight <- jmvcore::resolveQuo(jmvcore::enquo(quipsWeight))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rob2Study), rob2Study, NULL),
            `if`( ! missing(rob2D1), rob2D1, NULL),
            `if`( ! missing(rob2D2), rob2D2, NULL),
            `if`( ! missing(rob2D3), rob2D3, NULL),
            `if`( ! missing(rob2D4), rob2D4, NULL),
            `if`( ! missing(rob2D5), rob2D5, NULL),
            `if`( ! missing(rob2Overall), rob2Overall, NULL),
            `if`( ! missing(rob2Weight), rob2Weight, NULL),
            `if`( ! missing(rob2ClusterStudy), rob2ClusterStudy, NULL),
            `if`( ! missing(rob2ClusterD1), rob2ClusterD1, NULL),
            `if`( ! missing(rob2ClusterD1b), rob2ClusterD1b, NULL),
            `if`( ! missing(rob2ClusterD2), rob2ClusterD2, NULL),
            `if`( ! missing(rob2ClusterD3), rob2ClusterD3, NULL),
            `if`( ! missing(rob2ClusterD4), rob2ClusterD4, NULL),
            `if`( ! missing(rob2ClusterD5), rob2ClusterD5, NULL),
            `if`( ! missing(rob2ClusterOverall), rob2ClusterOverall, NULL),
            `if`( ! missing(robinsIStudy), robinsIStudy, NULL),
            `if`( ! missing(robinsID1), robinsID1, NULL),
            `if`( ! missing(robinsID2), robinsID2, NULL),
            `if`( ! missing(robinsID3), robinsID3, NULL),
            `if`( ! missing(robinsID4), robinsID4, NULL),
            `if`( ! missing(robinsID5), robinsID5, NULL),
            `if`( ! missing(robinsID6), robinsID6, NULL),
            `if`( ! missing(robinsID7), robinsID7, NULL),
            `if`( ! missing(robinsIOverall), robinsIOverall, NULL),
            `if`( ! missing(robinsIWeight), robinsIWeight, NULL),
            `if`( ! missing(robinsEStudy), robinsEStudy, NULL),
            `if`( ! missing(robinsED1), robinsED1, NULL),
            `if`( ! missing(robinsED2), robinsED2, NULL),
            `if`( ! missing(robinsED3), robinsED3, NULL),
            `if`( ! missing(robinsED4), robinsED4, NULL),
            `if`( ! missing(robinsED5), robinsED5, NULL),
            `if`( ! missing(robinsED6), robinsED6, NULL),
            `if`( ! missing(robinsED7), robinsED7, NULL),
            `if`( ! missing(robinsEOverall), robinsEOverall, NULL),
            `if`( ! missing(robinsEWeight), robinsEWeight, NULL),
            `if`( ! missing(quadas2Study), quadas2Study, NULL),
            `if`( ! missing(quadas2D1), quadas2D1, NULL),
            `if`( ! missing(quadas2D2), quadas2D2, NULL),
            `if`( ! missing(quadas2D3), quadas2D3, NULL),
            `if`( ! missing(quadas2D4), quadas2D4, NULL),
            `if`( ! missing(quadas2Overall), quadas2Overall, NULL),
            `if`( ! missing(quadas2Weight), quadas2Weight, NULL),
            `if`( ! missing(quipsStudy), quipsStudy, NULL),
            `if`( ! missing(quipsD1), quipsD1, NULL),
            `if`( ! missing(quipsD2), quipsD2, NULL),
            `if`( ! missing(quipsD3), quipsD3, NULL),
            `if`( ! missing(quipsD4), quipsD4, NULL),
            `if`( ! missing(quipsD5), quipsD5, NULL),
            `if`( ! missing(quipsD6), quipsD6, NULL),
            `if`( ! missing(quipsOverall), quipsOverall, NULL),
            `if`( ! missing(quipsWeight), quipsWeight, NULL))

    for (v in rob2D1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2D2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2D3) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2D4) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2D5) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2Overall) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2ClusterD1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2ClusterD1b) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2ClusterD2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2ClusterD3) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2ClusterD4) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2ClusterD5) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in rob2ClusterOverall) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsID1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsID2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsID3) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsID4) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsID5) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsID6) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsID7) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsIOverall) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsED1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsED2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsED3) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsED4) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsED5) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsED6) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsED7) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in robinsEOverall) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quadas2D1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quadas2D2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quadas2D3) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quadas2D4) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quadas2Overall) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quipsD1) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quipsD2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quipsD3) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quipsD4) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quipsD5) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quipsD6) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in quipsOverall) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- robOptions$new(
        tool = tool,
        rob2Study = rob2Study,
        rob2D1 = rob2D1,
        rob2D2 = rob2D2,
        rob2D3 = rob2D3,
        rob2D4 = rob2D4,
        rob2D5 = rob2D5,
        rob2Overall = rob2Overall,
        rob2Weight = rob2Weight,
        rob2ClusterStudy = rob2ClusterStudy,
        rob2ClusterD1 = rob2ClusterD1,
        rob2ClusterD1b = rob2ClusterD1b,
        rob2ClusterD2 = rob2ClusterD2,
        rob2ClusterD3 = rob2ClusterD3,
        rob2ClusterD4 = rob2ClusterD4,
        rob2ClusterD5 = rob2ClusterD5,
        rob2ClusterOverall = rob2ClusterOverall,
        robinsIStudy = robinsIStudy,
        robinsID1 = robinsID1,
        robinsID2 = robinsID2,
        robinsID3 = robinsID3,
        robinsID4 = robinsID4,
        robinsID5 = robinsID5,
        robinsID6 = robinsID6,
        robinsID7 = robinsID7,
        robinsIOverall = robinsIOverall,
        robinsIWeight = robinsIWeight,
        robinsEStudy = robinsEStudy,
        robinsED1 = robinsED1,
        robinsED2 = robinsED2,
        robinsED3 = robinsED3,
        robinsED4 = robinsED4,
        robinsED5 = robinsED5,
        robinsED6 = robinsED6,
        robinsED7 = robinsED7,
        robinsEOverall = robinsEOverall,
        robinsEWeight = robinsEWeight,
        quadas2Study = quadas2Study,
        quadas2D1 = quadas2D1,
        quadas2D2 = quadas2D2,
        quadas2D3 = quadas2D3,
        quadas2D4 = quadas2D4,
        quadas2Overall = quadas2Overall,
        quadas2Weight = quadas2Weight,
        quipsStudy = quipsStudy,
        quipsD1 = quipsD1,
        quipsD2 = quipsD2,
        quipsD3 = quipsD3,
        quipsD4 = quipsD4,
        quipsD5 = quipsD5,
        quipsD6 = quipsD6,
        quipsOverall = quipsOverall,
        quipsWeight = quipsWeight,
        summaryPlot = summaryPlot,
        trafficPlot = trafficPlot,
        combinedPlot = combinedPlot,
        combinedOrder = combinedOrder,
        combinedTags = combinedTags,
        colour = colour,
        pointSize = pointSize)

    analysis <- robClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

